export enum TiempoPlan {
  VISTA = 'VISITA',
  DIEZ_DIAS = 'DIEZ_DIAS',
  QUINCE_DIAS = 'QUINCE_DIAS',
  UNA_SEMANA = 'UNA_SEMANA',
  DOS_SEMANAS = 'DOS_SEMANAS',
  MENSUAL = 'UN_MES',
  TRIMESTRAL = 'TRES_MESES',
  SEMESTRAL = 'SEIS_MESES',
  ANUAL = 'UN_ANIO'
}
